## 5.1 简单语句

## 5.2 语句作用域

## 5.3 条件语句

## 5.4 迭代语句

## 5.5 跳转语句

## 5.5 try语句块和异常处理
<!-- [C++][throw表达式] -->
- 异常检测部分使用throw表达式表示遇到了无法处理的问题，throw引发（raise）了异常
```C++
    if(item1.isbn() != item2.isbn()){
        throw runtime_error("Data must refer to same ISBN");
    }
```

<!-- [C++][try语句块] -->
```C++
    try{
        //正常程序逻辑
        //可能抛出错误
    } catch(exception-declaration){
        handle-statements
    } catch(exception-declaration){
        handle-statements
    }...
```
- 如果没有找到匹配的catch子句，程序转到名为terminate的标准库函数，执行该函数将导致程序非正常退出
- 如果没有任何try语句块定义的异常，也会terminate终止当前程序的执行

<!-- [C++][标准异常] -->
- 标准库定义的一组类，用于报告标准库函数遇到的问题
- 定义在4个头文件中
  - exception头文件：只报告异常的发生，不提供额外信息
  - stdexcept头文件：定义了几种常见的异常类
  - new头文件：定义了bad_alloc异常类型
  - type_info头文件：定义了bad_cast异常类型


<!-- [C++][stdexcept头文件] -->
- exception
- runtime_error 运行时检测到的问题
- range_error 运行时错误，结果超出有意义的值域范围
- overflow_error 运行时错误，计算上溢
- underflow_error 运行时错误，计算下溢
- logic_error 程序逻辑错误
- domain_error 逻辑错误，参数对应的结果值不存在
- invaild_argument 逻辑错误，无效参数
- length_error 逻辑错误，试图创建一个超出该类型最大长度的对象
- out_of_range 逻辑错误，使用一个超出有效范围的值